version: "3.7"
services:
  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: 7.3
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
    restart: unless-stopped
    container_name: php_test
  composer:
    image: composer/composer:php7
    command: install
    volumes:
      - ./public_html/:/var/www/html/
    restart: unless-stopped
    container_name: php_composer
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: 2.4
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8181:80"
    volumes:
      - ./public_html/:/var/www/html/
    restart: unless-stopped
    container_name: apache_test
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3316:3306"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "dbtest"
      MYSQL_USER: "otherUser"
      MYSQL_PASSWORD: "password"
    container_name: mysql
networks:
  frontend:
  backend:
volumes:
    data:
